[package]
name = "lynchpin-term-layout"
version = "0.1.0"
edition = "2024"

[dependencies]
lynchpin-term-realize = { path = "../lynchpin-term-realize" }
lynchpin-library = { path = "../lynchpin-library" }
typst = { workspace = true }
crossterm = "0.29"
unicode-width = "0.2"
unicode-math-class = "0.1"
ecow = "0.2"
comemo = "0.5"
rustc-hash = "2.1.2"
smallvec = { version = "1.11", features = ["union"] }
