[package]
name = "lynchpin-layout-ng"
version = "0.1.0"
edition = "2024"

[dependencies]
lynchpin-library-ng = { path = "../lynchpin-library-ng" }
lynchpin-term-realize = { path = "../lynchpin-term-realize" }
typst = { workspace = true }
typst-library = { workspace = true }
typst-macros = "0.14"
typst-utils = "0.14"
typst-syntax = "0.14"
typst-timing = "0.14"
typst-assets = "0.14"
crossterm = "0.29"
unicode-width = "0.2"
ecow = "0.2"
comemo = "0.5"
bumpalo = { version = "3", features = ["boxed", "collections"] }
smallvec = "1"
rustc-hash = "2"
kurbo = "0.12"
rustybuzz = "0.20"
ttf-parser = "0.25"
hypher = "0.1"
az = "1.2"
either = "1"
unicode-bidi = "0.3"
unicode-math-class = "0.1"
unicode-script = "0.5"
unicode-segmentation = "1"
icu_properties = "1.4"
icu_provider = "1.4"
icu_provider_adapters = "1.4"
icu_provider_blob = "1.4"
icu_segmenter = "1.4"
memchr = "2"
tracing = { workspace = true }
